name: system_network_proxy_platform_interface
description: A new flutter plugin project.
version: 0.0.1
author:
homepage: https://github.com/liudonghua123/system_network_proxy

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.8.0