name: Pipeline

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  publish_platform_interface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ">> publish system_network_proxy_platform_interface <<"
        id: publish
        uses: liudonghua123/dart-package-publisher@dev
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: system_network_proxy_platform_interface
          skipTests: true
          dryRunOnly: true

  publish_platform:
    needs: [publish_platform_interface]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          [
            "system_network_proxy_web",
            "system_network_proxy_macos",
            "system_network_proxy_linux",
            "system_network_proxy_windows",
          ]
    steps:
      - uses: actions/checkout@v2
      - name: ">> publish ${{ matrix.platform }} <<"
        id: publish
        uses: liudonghua123/dart-package-publisher@dev
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: ${{ matrix.platform }}
          skipTests: true
          dryRunOnly: true

  publish:
    needs: [publish_platform_interface, publish_platform]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ">> publish system_network_proxy <<"
        id: publish
        uses: liudonghua123/dart-package-publisher@dev
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: system_network_proxy
          skipTests: true
          dryRunOnly: true
